spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://155.94.201.186:3306/bugs?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: bugs
    password: 1dcc7765a1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  mail:
#    port: 25
#    username: 2513512588@qq.com
#    password: pgkyvgtdqxcedjih
#    protocol: smtp
#    default-encoding: utf-8
#    host: smtp.qq.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
server:
  port: 8095
mybatis:
  mapper-locations: classpath:/mapper/*.xml
manager:
  username: root
  password: $2a$10$ZKSOz0KVH8xCGF9Osy0cleVaLixa5ipoaFseVzUWMzdGJnKbwKUNq
email:
  username: 2513512588@qq.com
  password: pgkyvgtdqxcedjih
  #bugzilla的发件人
  sender: pengjianmim@qq.com
jmeter:
  path: D:/runtime/apache-jmeter-5.4.1/bin/
tomcat:
  path: D:/runtime/apache-tomcat-9.0.39/bin
